### ISSUE TITLE
[meta] Add audio recording capability

### ISSUE THREAD

**Issue by MaHaWo** [ssciwr/iSparrow#23]
**What's the overarching idea and why is this additional feature necessary?**
Sparrow currently has no autonomous audio recording functionality of its own. 

**Describe into what individual steps/features your suggestion decays, and outline their basic ideas in one sentence each**
- [x] figure out which library to use to interface with the microphone. `PyAudio` is an option, and `birdnetlib` shows how to use linux's `arecord`. But could also go for [pvrecorder](https://github.com/Picovoice/pvrecorder). #28 
- [x] #28
- [x] figure out possible multiprocessing for concurrent running and analyzing
- [ ] integrate into runner system

**Comment by iulusoy** [comment]
Also possible as a separate smaller package that chops up a stream and places snippets into a `watch_folder` for the runner to analyse.

**Comment by iulusoy** [comment]
Maybe there are libraries that can be used?

**Comment by MaHaWo** [comment]
There's [pvrecorder](https://github.com/Picovoice/pvrecorder) that does the chopping up. It's a rather big dependency, but does not rely on external dependencies. 

Then there's also `arecord`  (available on linux as a separate app/package) which we would have to call via python and wrap in a class that allows to change the parameters upon model exchange (demanded sampling rate and interval length of different models can be different, and offloading this to the preprocessor to resample everything and handle mismatching lengths imho introduces too much overhead and complexity).  

Finally, there's `pyaudio`  and `python-sounddevice` that can be used to write the stream-chop-save functionality with. 
Probably comes down to ease of use and simplicity. [`bridnetlib` examples use `arecord` on linux](https://github.com/joeweiss/birdnetlib/blob/main/examples/linux_arecord_and_watch.py)

**Comment by MaHaWo** [comment]
Tried out different ones today. `pyaudio` seems to work best, but does depend on the external `portaudio`.

**Comment by MaHaWo** [comment]
This now happens in [iSparrowRecord](https://github.com/ssciwr/iSparrowRecord). Closed
