### ISSUE TITLE
[meta] Set up pytest properly 

### ISSUE THREAD

**Issue by MaHaWo** [ssciwr/iSparrow#8]
- [x] separate doctests and unittests? 
- [x] add code coverage to github workflow. Make sure to check branch coverage as well.  #26 
- [x] make sure it runs the same way on win, mac, ubuntu
